// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ii1oyU9i6oC4gme6KqTQSA
// Component: XKUwjV76ep
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_keynumbers.module.css"; // plasmic-import: ii1oyU9i6oC4gme6KqTQSA/projectcss
import sty from "./PlasmicTestComponent.module.css"; // plasmic-import: XKUwjV76ep/css
import _7E681A4E224Ae6644B74Dbe42F162823JpegZJk6PwOj5 from "./images/_7E681A4E224Ae6644B74Dbe42F162823Jpeg.jpeg"; // plasmic-import: zJk6pwOj5/picture

export const PlasmicTestComponent__VariantProps = new Array();

export const PlasmicTestComponent__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicTestComponent__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
    >
      <p.PlasmicImg
        data-plasmic-name={"img"}
        data-plasmic-override={overrides.img}
        alt={""}
        className={classNames(sty.img)}
        displayHeight={"auto"}
        displayMaxHeight={"none"}
        displayMaxWidth={"100%"}
        displayMinHeight={"0"}
        displayMinWidth={"0"}
        displayWidth={"auto"}
        loading={"lazy"}
        src={{
          src: _7E681A4E224Ae6644B74Dbe42F162823JpegZJk6PwOj5,
          fullWidth: 564,
          fullHeight: 564,
          aspectRatio: undefined
        }}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "img"],
  img: ["img"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicTestComponent__ArgProps,
          internalVariantPropNames: PlasmicTestComponent__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicTestComponent__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTestComponent";
  } else {
    func.displayName = `PlasmicTestComponent.${nodeName}`;
  }
  return func;
}

export const PlasmicTestComponent = Object.assign(
  // Top-level PlasmicTestComponent renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    // Metadata about props expected for PlasmicTestComponent
    internalVariantProps: PlasmicTestComponent__VariantProps,
    internalArgProps: PlasmicTestComponent__ArgProps
  }
);

export default PlasmicTestComponent;
/* prettier-ignore-end */
